<div class="form-list">
    <div id="shipment_form"></div>
    <div id="keen_option_default_method" class="form-group">

        <input id="keen_set_as_default"
               type="checkbox"/>
        <label for="keen_set_as_default">Deze instelling doorkopieren voor alles (met uitzondering van lastmile bestellingen).</label><br/>
    </div>
    <div>
        <button title="Opslaan" type="button" onclick="jetSaveShipmentSettingsBox();" class=""><span>Opslaan</span>
        </button>
    </div>
</div>
<input type="hidden" id="keen_default_order" name="default_order" value=""/>
<input type="hidden" id="keen_entity_id" name="entity_id" value=""/>
<input type="hidden" id="keen_increment_id" name="increment_id" value=""/>
