<?php
$lastmilePriceDpdSaterday = $this->getLastmilePriceDpdSaterday();
$lastmileSaterdayDpdTime = $this->getLastmileSaterdayDpdTime();

$arrSaterdays = array();
for ($x = 0; $x <= 4; $x++
) {

    if ($x == 0) {
        if (Mage::getModel('core/date')->date('w') == 5 && Mage::getModel('core/date')->date('His') > $lastmileSaterdayDpdTime) {
            // to late...
        } else {
            $arrSaterdays[Mage::getModel('core/date')->date('Ymd', strtotime("next saturday"))] = Mage::getModel('core/date')->date('d F Y', strtotime("next saturday"));
        }

    } else {
        $arrSaterdays[Mage::getModel('core/date')->date('Ymd', strtotime("next saturday + $x week"))] = Mage::getModel('core/date')->date('d F Y', strtotime("next saturday + $x week"));

    }
}


echo '<h1>Kies een zaterdag uit:</h1>';
?>

<div class="element-list">
    <?php
    if ($arrSaterdays) :
        foreach ($arrSaterdays as $key => $val) :
            if (Mage::helper('jetverzendt_shipping')->isDutchPublicHoliday($key)) {
                continue;
            }
            ?>
            <div class="row">
                <div class="col-100">
                    Zaterdag <?php echo $this->escapeHtml($val); ?>

                    <a href="javascript:void(0);"  onclick="$('jet_last_mile_choice').show(); $('lastmile_deliverdate').setValue('<?php echo $this->escapeHtml($key) ?>');  $('lastmile_service').setValue('DPD'); $('lastmile_type').setValue('dpd_saterday');   $('jet_name_lastmile').update('Zaterdaglevering: <?php echo $this->escapeHtml($val) ?>'); $('lastmile_lightbox').hide(); setService();  $('clear_last_mile').show(); return false; ">Selecteer</a>

                    <span class="jet_special_price"><?php
                        echo Mage::helper('core')->currency($lastmilePriceDpdSaterday, true, false);
                        ?></span>
                </div>
            </div>
            <?php
        endforeach;
    else :
        ?>
        Helaas... er kunnen geen data getoond worden.
        <?php
    endif
    ?>
</div>


<input type="hidden" name="lastmile_deliverdate" id="lastmile_deliverdate"/>


