<?php
$lastmilePriceDpdSaterday = $this->getLastmilePriceDpdSaterday();
$lastmileSaterdayDpdTime  = $this->getLastmileSaterdayDpdTime();

$arrSaterdays = array();
for ($x = 0; $x <= 4; $x++
) {

    if ($x == 0) {
        if (Mage::getModel('core/date')->date('w') == 5 && Mage::getModel('core/date')->date('His') > $lastmileSaterdayDpdTime) {
            // to late...
        } else {
            $arrSaterdays[Mage::getModel('core/date')->date('Ymd', strtotime("next saturday"))] = Mage::getModel('core/date')->date('d F Y', strtotime("next saturday"));
        }

    } else {
        $arrSaterdays[Mage::getModel('core/date')->date('Ymd', strtotime("next saturday + $x week"))] = Mage::getModel('core/date')->date('d F Y', strtotime("next saturday + $x week"));

    }
}


echo '<h1>Kies een zaterdag uit:</h1>';

echo '<table width=\'92%\' class=\'deliver_dates\'>';
echo '<tbody>';
if ($arrSaterdays) {
    foreach ($arrSaterdays as $key => $val) {
        if (Mage::helper('jetverzendt_shipping')->isDutchPublicHoliday($key)) {
            continue;
        }

        echo '<tr>';
        echo '  <td>Zaterdag ' . $val;


        echo ' <a onclick="$(\'jet_last_mile_choice\').show(); $(\'lastmile_deliverdate\').setValue(\'' . $this->escapeHtml($key)
            . '\');  $(\'lastmile_service\').setValue(\'DPD\'); $(\'lastmile_type\').setValue(\'dpd_saterday\');   $(\'jet_name_lastmile\').update(\'Zaterdaglevering: ' . $this->escapeHtml($val)
            . '\'); $(\'lastmile_lightbox\').hide(); return false; ">';
        echo 'Selecteer';
        echo '</a>';

        echo '<span class="jet_special_price"> + ';
        echo Mage::helper('core')->currency($lastmilePriceDpdSaterday, true, false);
        echo '</span>';

        echo '</td>';

        echo '</tr>';

    }


} else {

    echo '<tr><td colspan="5">Helaas... er kunnen geen data getoond worden. </td></tr>';
}

echo '<tbody>';

echo '</table>';

?>


<input type="hidden" name="lastmile_deliverdate" id="lastmile_deliverdate"/>


