<?php
$defaultShipmentSetting = ( Mage::getStoreConfig( 'jetverzendt/default_shipment_form' ) );
$orders                 = $this->getOrders();
if ( count( $orders ) == 0 ) :
	?>
	<div>
		<h3>Er zijn geen bestellingen om te versturen...</h3>
	</div>
<?php else : ?>
	<div class="content-header">
		<table cellspacing="0">
			<tr>
				<td style="width:50%;"><h3 class="icon-head head-sales-order">Weet u zeker dat u deze orders naar Jet
						Verzendt wilt versturen?
					</h3></td>
				<td class="form-buttons">
					<button title="Verstuur orders naar Jet Verzendt" type="button" onclick="jetStartSendOrders(); "
					        id="jet_button_send_orders"
					        class=""><span>Verstuur naar Jet Verzendt</span>
					</button>
				</td>
			</tr>
		</table>
	</div>

	<div>
		<div class="grid">
			<table class="data" cellspacing="0">
				<thead>
				<tr class="headings">
					<th class=" last"><span class="sort-title">Order #</span>
					</th>
					<th class=" last"><span class="sort-title">Naam</span>
					</th>
					<th class=" last"><span class="sort-title">Adres</span>
					</th>
					<th class=" last"><span class="sort-title">Plaats</span>
					</th>
					<th class=" last"><span class="sort-title">Aantal items</span>
					</th>
					<th class=" last"><span class="sort-title">Lastmile</span>
					</th>
					<th class=" last" style="width: 500px"><span class="sort-title">Verzendspecificaties</span>
					</th>
					<th class="" style="width: 300px"><span class="sort-title">Jet Verzendt status</span>
					</th>
				</tr>
				</thead>
				<tbody>
				<?php
				if ( $orders ) :
					$i = 0;
					foreach ( $orders as $order ) :
						?>
						<tr class="<?php echo ( $i % 2 ) ? 'even' : 'odd' ?> " title=""
						    id="jet_order_<?php echo $this->escapeHtml( $order->getEntityId() ); ?>">
							<td>
								<?php echo $this->escapeHtml( $order->getIncrementId() ); ?>
								<input type="hidden" class="order_ids" id="order_id_<?php echo $i ?>"
								       value="<?php echo $order->getEntityId(); ?>"/>
								<input type="hidden" id="order_increment_<?php echo $order->getEntityId(); ?>"
								       value="<?php echo $order->getIncrementId(); ?>"/>
								<input type="hidden" id="order_send_status_<?php echo $order->getEntityId(); ?>"
								       value="0"/>

							</td>
							<td>
								<?php echo $this->escapeHtml(
									$order->getShippingAddress()->getFirstname() . ' ' . $order->getShippingAddress()->getMiddlename()
									. ' '
									. $order->getShippingAddress()->getLastname()
								); ?>

							</td>
							<td>
								<?php echo $this->escapeHtml( $order->getShippingAddress()->getData( 'street' ) ); ?>
							</td>
							<td>
								<?php echo $this->escapeHtml( $order->getShippingAddress()->getCity() ); ?>
							</td>
							<td>
								<div class="jet_tooltip">
									<?php echo $this->escapeHtml( $order->getTotalItemCount() ); ?>
									<span class="jet_tooltiptext"><?php $items = $order->getAllVisibleItems();
										foreach ( $items as $item ):
											echo ( $item->getQtyOrdered() * 1 ) . ' x ' . $item->getName() . '<br/>';
										endforeach;
										?></span>
								</div>
							</td>
							<td>
								<?php
								if ( $order->getJetLastMile() ) {
									$jetDefaultOrder = 0;

									$lastMileData = unserialize( $order->getJetLastMile() );

									if ( isset( $lastMileData['type'] )
									     && $lastMileData['type'] == 'dhl_deliverdate'
									     && isset( $lastMileData['lastmile_service'] )
									     && isset( $lastMileData['lastmile_deliverdate'] )
									     && isset( $lastMileData['lastmile_deliverperiod'] )
									     && isset( $lastMileData['lastmile_deliverevening'] )
									) {
										$jetShipmentSetting = 'product=' . $lastMileData['lastmile_service'] . '&service=DHL_FOR_YOU' . ( ( $lastMileData['lastmile_deliverevening'] == 1 ) ? '&evening=1' : '' );
										$jetLastmileComment = '<strong>Tijdsvaklevering op: ' . $this->escapeHtml( $lastMileData['lastmile_deliverdate'] ) . '</strong>';
										$jetLastmileComment .= '<br/>' . ( ( $lastMileData['lastmile_deliverevening'] == 1 ) ? 'Avondlevering.' : '' );

									}

									if ( isset( $lastMileData['type'] )
									     && $lastMileData['type'] == 'dpd_saterday'
									) {
										$jetLastmileComment = '<strong>DPD zaterdaglevering op: ' . $this->escapeHtml( date( 'd-m-Y', strtotime( $lastMileData['lastmile_deliverdate'] ) ) ) . '</strong>';
										$jetShipmentSetting = 'product=DPD&service=CL&saturday_delivery=1';
									}

									if ( isset( $lastMileData['type'] )
									     && $lastMileData['type'] == 'fadello'
									) {
										$jetLastmileComment = '<strong>Same Day Delivery</strong>';
										$jetShipmentSetting = 'product=Fadello&service=DEFAULT';
									}


									if ( isset( $lastMileData['type'] )
									     && $lastMileData['type'] == 'parcelshop'
									     && isset( $lastMileData['lastmile_service'] )
									     && isset( $lastMileData['lastmile_parcelshop_id'] )
									) {
										if ( $lastMileData['lastmile_service'] == 'DPD' ) {
											$jetShipmentSetting = 'product=DPD&service=PARCELSHOP&parcel_shop_id=' . $lastMileData['lastmile_parcelshop_id'];
										} else {
											$jetShipmentSetting = 'product=' . $lastMileData['lastmile_service'] . '&service=PARCEL_SHOP&parcel_shop_id=' . $lastMileData['lastmile_parcelshop_id'];

										}
										$jetLastmileComment = '<strong>Parcelshop: ' . $this->escapeHtml( $lastMileData['lastmile_parcelshop_id'] ) . '</strong>';
										$jetLastmileComment .= '<br/>' . $this->escapeHtml( $lastMileData['lastmile_parcelshop_description'] );
									}

								} else {

									$jetShipmentSetting = isset( $defaultShipmentSetting ) ? $this->escapeHtml( $defaultShipmentSetting ) : '';
									$jetDefaultOrder    = 1;
									$jetLastmileComment = '';


								}

								echo $jetLastmileComment;

								?>
							</td>
							<td class="last" id="jet_deliver_<?php echo $order->getEntityId(); ?>">
								<input type="hidden"
								       id="jet_default_order_<?php echo $order->getEntityId(); ?>"
								       value="<?php echo $this->escapeHtml( $jetDefaultOrder ); ?>"/>

								<input type="hidden"
								       id="jet_shipment_setting_<?php echo $order->getEntityId(); ?>"
								       value="<?php echo $this->escapeHtml( $jetShipmentSetting ); ?>"/>

								<span id="jet_order_text_<?php echo $order->getEntityId(); ?>"></span>
								<a href="javascript:void(0);"
								   onclick="jetSetupOrderSetting(<?php echo $order->getEntityId(); ?>); $('jet_lightbox').show(); return false;">Bekijk/wijzig</a>
							</td>
							<td class="jet_order_status"
							    id="jet_order_status_<?php echo $order->getEntityId(); ?>"></td>
						</tr>
						<?php
						$i ++;
					endforeach;
				endif; ?>
				</tbody>
			</table>
		</div>
	</div>

	<div class="jet_lightbox" id="jet_lightbox" style="display: none">
		<div class="jet_lightbox_close" onclick="jetCloseLightbox();"><span>x</span></div>
		<div>
			<form id="jetverzendt_shipment_form" action="<?php echo Mage::getModel( 'adminhtml/url' )->getUrl(
				'adminhtml/jetverzendt/sendorders'
			); ?>">
				<h3>Verzendinstellingen:</h3>
				<div class="jetverzendt_shipment_form_message"></div>
				<?php
				$block = $this->getLayout()->createBlock( 'core/template' );
				echo $block->setTemplate( 'jetverzendt/sales/order/shipment/create/jetverzendt_shipment.phtml' )->toHtml();
				?>
			</form>

		</div>
	</div>
	<script type="text/javascript">
		var jet_shippable_orders = new Array;
		var jet_send_status = 0;
		var jet_errors = 0;

		//<![CDATA[
		document.observe("dom:loaded", function () {
			setTimeout(function () {
				setJetShipmentAndOrderFields();
				jetUpdateTextMessage();
			}, 500);

		});


		editForm = new varienForm('edit_form');

		function jetSaveShipmentSettingsBox() {
			// Save form values to hidden field
			if ($('jet_entity_id') != undefined) {
				var id = $('jet_entity_id').getValue();
				if (id) {
					var inputs = $("jetverzendt_shipment_form").getElements();
					var visibleInputs = inputs.grep({
						match: function (elem) {
							if (elem.readAttribute('name') == 'default_order' || elem.readAttribute('name') == 'entity_id' || elem.readAttribute('name') == 'increment_id') return false;
							return true;
						}
					});
					var serialized = Form.serializeElements(visibleInputs);
					if (serialized) {
						if ($('jet_shipment_setting_' + id) != undefined) {
							$('jet_shipment_setting_' + id).setValue(serialized);
						}

						// check if to copy this values to other default fields
						var set_as_default = $('jet_set_as_default').checked;
						if (set_as_default) {

							$$(".order_ids").each(
								function (item) {
									if (($('jet_default_order_' + item.getValue()) != undefined)) {
										if ($('jet_default_order_' + item.getValue()).getValue() == 1) {
											if ($('jet_shipment_setting_' + item.getValue()) != undefined) {
												$('jet_shipment_setting_' + item.getValue()).setValue(serialized);
											}
										}
									}
								}
							)
						}
					}
				}
			}
			jetUpdateTextMessage();
			$('jet_lightbox').hide();

		}


		function jetSetupOrderSetting(id) {

			$('jetverzendt_shipment_form').reset();

			// Set entity ID
			$('jet_entity_id').setValue(id);

			// Set increment ID
			if ($('order_increment_' + id) != undefined) {
				$('jet_increment_id').setValue($('order_increment_' + id).getValue());
			} else {
				alert('Er is iets fout gegaan (1)');
			}

			// Set form values
			if ($('jet_shipment_setting_' + id) != undefined) {
				var value = $('jet_shipment_setting_' + id).getValue();

				var arrayOfStrings = value.split('&');
				for (i = 0; i < arrayOfStrings.length; i++) {
					value = arrayOfStrings[i];
					arrValue = value.split('=');
					if ($('jet_' + arrValue[0]) != undefined && arrValue[0] != 'entity_id' && arrValue[0] != 'increment_id') {
						$('jet_' + arrValue[0]).setValue(arrValue[1]);
					}
				}

				// Jet Amount default 1
				if (!$('jet_amount').getValue()) {
					$('jet_amount').setValue(1)
				}

				// Jet Amount
				if (!$('jet_weight').getValue()) {
					$('jet_weight').setValue(1)
				}


				if ($('jet_default_order_' + id) != undefined && $('jet_default_order_' + id).getValue() == 1) {
					$('jet_default_order').setValue(1);
					$('jet_option_default_method').show();
				} else {
					$('jet_default_order').setValue(0);
					$('jet_option_default_method').hide();
				}


				setJetShipmentAndOrderFields();
			} else {
				alert('Er is iets fout gegaan (2)');
			}
		}


		function jetGetFormValueByName(id, name) {
			if ($('jet_shipment_setting_' + id) != undefined) {
				var value = $('jet_shipment_setting_' + id).getValue();

				var arrayOfStrings = value.split('&');
				for (i = 0; i < arrayOfStrings.length; i++) {
					value = arrayOfStrings[i];
					arrValue = value.split('=');
					if (arrValue[0] == name) {
						return arrValue[1];
					}
				}

			}
			return '';
		}

		function jetCloseLightbox() {
			$$(".jet_lightbox").each(
				function (item) {
					item.hide();
				}
			);
		}

		function jetUpdateTextMessage() {
			$$(".order_ids").each(
				function (item) {
					var order_text = '';
					if (($('jet_shipment_setting_' + item.getValue()) != undefined)) {
						order_text += jetGetFormValueByName(item.getValue(), 'product');
						order_text += ' / ';
						order_text += jetGetFormValueByName(item.getValue(), 'service');
						$('jet_order_text_' + item.getValue()).update(order_text);
					}
				}
			)
		}

		function jetCheckForm() {
			var status = true;
			$$(".jet_shipment_error").each(
				function (item) {
					item.removeClassName('jet_shipment_error');
				}
			);


			$$(".order_ids").each(
				function (item) {
					if (($('jet_shipment_setting_' + item.getValue()) != undefined)) {
						if (!$('jet_shipment_setting_' + item.getValue()).getValue()) {
							$('jet_order_' + item.getValue()).addClassName('jet_shipment_error');
							status = false;
						}
					} else {
						status = false;

					}
				}
			)
			return status;
		}

		function jetStartSendOrders() {
			jet_shippable_orders = [];
			jet_send_status = 0;
			jet_errors = 0;
			var i = 0;

			if (jetCheckForm()) {
				//saveDefaultShipmentForm();

				$$(".order_ids").each(
					function (item) {
						if (($('order_send_status_' + item.getValue()) != undefined)) {
							if ($('order_send_status_' + item.getValue()).getValue() == 0) {
								jet_shippable_orders[i++] = item.getValue();
							}
						}
					});

				if (jet_shippable_orders.length > 0) {
					$('jet_button_send_orders').addClassName('disabled');
					$('jet_button_send_orders').disable();
					jetSendOrderToJet(0);
				} else {
					alert('Er zijn geen orders om te versturen');
				}

			}
			else {
				alert('Enkele orders zijn niet volledig ingevuld. Wijzig dit om door te gaan.');
			}
		}


		function jetSendOrderToJet(i) {
			var order_id = jet_shippable_orders[i];

			jetSetupOrderSetting(order_id);
			$('jet_order_status_' + order_id).update('Bezig met versturen');

			$('jetverzendt_shipment_form').request({
				onComplete: function (t) {
					if (t.responseText == 1) {
						$('order_send_status_' + order_id).setValue(1);
						$('jet_order_status_' + order_id).update('<span class="jet_green">Order verzonden</span>');
					} else if (t.responseText == 2) {
						$('order_send_status_' + order_id).setValue(1);
						$('jet_order_status_' + order_id).update('<span class="jet_green">Order verzonden, geen verzending aangemaakt</span>');
					} else {
						jet_errors++;
						$('jet_order_status_' + order_id).update('<span class="jet_red">' + t.responseText + '</span>');
					}
					jet_send_status++;

					// when ready...
					if (jet_send_status == jet_shippable_orders.length) {
						if (jet_errors > 0) {
							if (jet_errors == 1) {
								alert('Het verzenden is afgerond. Er is ' + jet_errors + ' order mislukt.');
							} else {
								alert('Het verzenden is afgerond. Er zijn ' + jet_errors + ' orders mislukt.');
							}
						} else {
							alert('Verzenden is succesvol afgerond.');
						}

						$('jet_button_send_orders').removeClassName('disabled');
						$('jet_button_send_orders').enable();
					} else {
						i++;
						jetSendOrderToJet(i);
					}

				}
			});


		}


		//]]>
	</script>
<?php endif; ?>